Simplify interface and add support for ContT
Add `runFSMCont` compatible with `ContT` which does not implement `MonadCatch`
Hide PropertyM to simplify user's test code (safe on `lift`s)
`transition` is now `Action` which is `MonadReader` and `MonadWriter`
Add various combinators for defining transition and asserts

diff --git a/framework/cabal b/framework/cabal
--- a/framework/cabal
+++ b/framework/cabal
@@ -11,6 +11,9 @@ Commands:
     repl            Start the repl, by default on the the main library source.
     quick           Start the repl directly skipping cabal, this is useful developing
                     across multiple source trees at once.
+    watch           Watches filesystem for changes and stays running, compiles and gives quick feedback.
+                    Similarly to quick needs an entrypoint.
+                    To run tests use '-T EXPR' i.e. '-T Test.Pure.tests'
     demo            If this project has a demo application, this builds and runs it.
     exec            If this project has an executable, this builds and runs it.
     tags            Generate tags for this project.
@@ -18,13 +21,14 @@ Commands:
     init            Start a new project.
     update          Cabal update, but limited to retrieving at most once per day.
     clean           Remove compiled artifacts.
+    depend          Dependency organisation tooling check|deep-check|sync.
 EOF
     exit ${status}
 }
 
 fail () {
      message="${1:-}"
-     [ -z "$message" ] || echo message 1>&2
+     [ -z "$message" ] || echo "${message}" 1>&2
      usage 1 1>&2
 }
 
@@ -44,8 +48,10 @@ project_name () {
 initialize () {
     # sandbox has all sources
     project=$(project_name)
+    SANDBOX_DIR=.cabal-sandbox
     [ ! -f "${project}.sandbox" ] || {
-        SANDBOX="--sandbox $(cat ${project}.sandbox)"
+        SANDBOX_DIR=$(cat ${project}.sandbox)
+        SANDBOX="--sandbox ${SANDBOX_DIR}"
     }
 
     # sandbox initialized if required, this should support sandboxes in parent directories
@@ -56,7 +62,9 @@ initialize () {
     [ ! -f "$project.submodules" ] || {
         # submodules initialized if required, the "has it been done before" is pretty crude, but check is useful.
         cat $project.submodules | while read submodule; do
-            find "$submodule" -maxdepth 2 -name \*.cabal
+            if [ -d "$submodule" ]; then
+               find "$submodule" -maxdepth 2 -name \*.cabal
+            fi
         done | grep -q . || (
             cd $(git rev-parse --show-toplevel)
             git submodule init
@@ -64,8 +72,9 @@ initialize () {
         )
 
         cat $project.submodules | while read submodule; do
-            # ideally this would be conditional but yeh, stuff
-            cabal sandbox add-source ${SANDBOX:-} "$submodule"
+            if ! grep -q "${submodule}\"" ${SANDBOX_DIR}/add-source-timestamps; then
+                cabal sandbox add-source ${SANDBOX:-} "$submodule"
+            fi
         done
     }
 
@@ -87,7 +96,7 @@ run_build () {
 #
 run_test () {
     initialize
-    cabal test "$@"
+    cabal test --show-details=streaming "$@"
 }
 
 #
@@ -103,7 +112,28 @@ run_repl () {
 #
 run_quick () {
     initialize
-    ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') -isrc -itest test/test.hs
+    [ $# -eq 1 ] || fail "'quick' requires a single argument, specifying the entry point you want to load."
+    [ -f "$1" ] || fail "The entry point does not exist."
+    [ ! -d src ] || SRC_DIRS="-isrc"
+    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
+    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
+    ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} "$1"
+}
+
+#
+# Load up ghcid
+#
+run_watch () {
+    command -v ghcid >/dev/null 2>&1 || { echo >&2 "ghcid required not installed. To install: create a fresh cabal sandbox, cabal install ghcid and add to your \$PATH."; exit 1; }
+    initialize
+    [ $# -ge 1 ] || fail "Watch requires atleast one argument, specifying the entry point you want to load."
+    [ -f "$1" ] || fail "The entry point does not exist."
+    [ ! -d src ] || SRC_DIRS="-isrc"
+    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
+    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
+    ENTRY=$1
+    shift
+    ghcid -c "ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} \"$ENTRY\"" "$@"
 }
 
 #
@@ -114,26 +144,124 @@ run_clean () {
 }
 
 #
-# Build and run the configured demonstration executable.
+# Dependency tools.
 #
-run_demo () {
-    echo "Someone should really implement this."
-    exit 1
+
+# using this instead of git submodule foreach in the hope I can avoid recursive submodule init/updates (probably can't though, so this may be irrelevant).
+list_modules () {
+    [ $# -eq 1 ] || fail "list_modules requires a single argument, specifying the root of the project."
+    MODULES="$1/.gitmodules"
+    if [ -f "${MODULES}" ]; then
+        grep path "${MODULES}" | sed 's/.*= //'
+    fi
+}
+
+force_sync () {
+    [ $# -eq 1 ] || fail "force sync requires a single argument, specifying the root of the project."
+    SYNC_ROOT="$1"
+    (
+        cd "${SYNC_ROOT}" ## required for submodule commands on older versions of git
+        git fetch
+        git submodule init
+        git submodule update
+        git submodule sync
+    ) > /dev/null 2>&1
+}
+
+run_depend_check () {
+    TOP=$(git rev-parse --show-toplevel)
+    force_sync "${TOP}"
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            cd "${TOP}/${SUBMODULE}"
+            echo "$SUBMODULE"
+            git fetch > /dev/null 2>&1
+            OUT=$(git rev-list --left-right --count origin/master...)
+            BEHIND=$(echo $OUT | awk '{ print $1 }')
+            AHEAD=$(echo $OUT | awk '{ print $2 }')
+
+            if [ "$AHEAD" -eq 0 -a "$BEHIND" -eq 0 ]; then
+                echo '  `- [OK]'
+            elif [ "$AHEAD" -eq 0 -a "$BEHIND" -gt 0 ]; then
+                echo '  `- [WARNING] Behind master.'
+            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -eq 0 ]; then
+                echo '  `- [WARNING] Commits not on master.'
+            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -gt 0 ]; then
+                echo '  `- [WARNING] Commits not on master & behind master.'
+            fi
+        )
+    done
+}
+
+run_depend_deep_check () {
+    TOP=$(git rev-parse --show-toplevel)
+    force_sync "${TOP}"
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            echo "$SUBMODULE"
+            force_sync "${TOP}/${SUBMODULE}"
+            list_modules "${TOP}/${SUBMODULE}" | while read SUBSUBMODULE; do
+                if [ -e "${TOP}/${SUBSUBMODULE}" ]; then
+                    NESTED=$(cd "${TOP}/${SUBMODULE}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
+                    OUTER=$(cd "${TOP}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
+                    if [ "${NESTED}" = "${OUTER}" ]; then
+                        echo "  \`- [OK] ${SUBSUBMODULE}"
+                    else
+                        (
+                            cd "${TOP}/${SUBSUBMODULE}"
+                            git fetch > /dev/null 2>&1
+                            echo ${TOP}/${SUBSUBMODULE}
+                            OUT=$(git rev-list --left-right --count "${NESTED}...${OUTER}")
+                            BEHIND=$(echo $OUT | awk '{ print $1 }')
+                            AHEAD=$(echo $OUT | awk '{ print $2 }')
+                            echo "  \`- [WARNING] ${SUBSUBMODULE} is out of sync, outer commit ${OUTER}, nested ${NESTED}, outer is ${BEHIND} commits behind, ${AHEAD} commits ahead."
+                        )
+                    fi
+                else
+                    echo "  \`- [WARNING] Potentially missing dependency ${SUBSUBMODULE}"
+                fi
+            done
+        )
+    done
+}
+
+run_depend_sync () {
+    TOP=$(git rev-parse --show-toplevel)
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            echo "$SUBMODULE"
+            force_sync "${TOP}/${SUBMODULE}"
+
+            cd "${TOP}/${SUBMODULE}"
+            if git branch -a | grep -q origin/ambiata; then
+                git checkout ambiata
+                git merge origin/ambiata
+            else
+                git checkout master
+                git merge origin/master
+            fi
+
+            force_sync "${TOP}/${SUBMODULE}"
+        )
+    done
+}
+
+run_depend () {
+    [ $# -eq 1 ] || fail "'depend' requires a single argument, specifying the mode as one of [check|deep-check|sync]."
+
+    case "$1" in
+    check) run_depend_check ;;
+    deep-check) run_depend_deep_check ;;
+    sync) run_depend_sync;;
+    *) fail "Unknown mode [$1], expected one of [check|deep-check|sync]" ;;
+    esac
 }
 
 #
-# Build and run the configured application executable.
-#
-run_exec () {
-    echo "Someone should really implement this."
-    exit 1
-}
-
-#
-# Run hasktags on this project (building hlint if necessary).
+# Run hasktags on this project.
 #
 run_tags () {
-    # should install hasktags if it doesn't exist yet.
+    # TODO should install hasktags if it doesn't exist yet.
     hasktags -e src test main
 }
 
@@ -141,18 +269,8 @@ run_tags () {
 # Run hlint on this project (building hlint if necessary).
 #
 run_lint () {
-    # do something with hlint - need to work out best convention to build up
-    echo "Someone should really implement this."
-    exit 1
-}
-
-#
-# Initialize an empty project with a reasonable skeleton.
-#
-run_init () {
-    # make sure there is an empty directory and fill out skeleton
-    echo "Someone should really implement this."
-    exit 1
+    # TODO should install hlint if it doesn't exist yet.
+    hlint src test main
 }
 
 #
@@ -180,6 +298,6 @@ esac
 
 MODE="$1"; shift
 case "$MODE" in
-build|test|repl|quick|demo|exec|tags|lint|init|update|clean) run_$MODE "$@" ;;
+build|test|repl|quick|tags|lint|update|clean|depend|watch) run_$MODE "$@" ;;
 *) fail "Unknown mode: $MODE"
 esac
